---
title: "Arrowhead Data"
author: "Spiro Stilianoudakis"
date: "April 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading in the TAD boundary data

```{r}
#The data comes from the paper by Rao, Huntley, et. al titled,
#"A three-dimensional map of the human genome at kilobase resolution reveals prinicples of chromatin looping"
#GEO accession: GSE63525

#The contact domain annoation file is named: GSE63525_GM12878_primary+replicate_Arrowhead_domainlist.txt
#The arrowhead algorithm was used to determine domains

#The columns are defined as follows: 
#chromosome1    x1    x2    chromosome2    y1    y2    color    corner_score    Uvar    Lvar    Usign    Lsign
#Explanations of each field are as follows:
#chromosome = the chromosome that the domain is located on
#x1,x2/y1,y2 = the interval spanned by the domain (contact domains manifest as squares on the diagonal of a Hi-C matrix and as such: x1=y1, x2=y2)
#color = the color that the feature will be rendered as if loaded in Juicebox 


setwd("C:/Users/Spiro Stilianoudakis/Documents/TAD_data_analysis/data")

#"chr" was appended to the chr1 column of the
#GSE63525_GM12878_primary+replicate_Arrowhead_domainlist txt file
#in the commandline and renamed arrowhead
arrowhead <- read.table("arrowhead.txt", header=T)
dim(arrowhead)

```

# Changing the characteristics of the data

```{r}
colnames(arrowhead)[1] <- "Chromosome"
colnames(arrowhead)[2] <- "Start"
colnames(arrowhead)[3] <- "End"
head(arrowhead)
table(arrowhead$Chromosome)

arrowheadnum <- arrowhead[-which(arrowhead$Chromosome=="chrX"),]
arrowheadx <- arrowhead[which(arrowhead$Chromosome=="chrX"),]

arrowheadnum2 <- arrowheadnum[order(as.numeric(substr(arrowheadnum$Chromosome,4,5)), arrowheadnum$Start),]
arrowheadx2 <- arrowheadx[order(arrowheadx$Start),]

arrowhead_data <- rbind.data.frame(arrowheadnum2,arrowheadx2)

```

# Writing the data to a file named "arrowhead.txt"

```{r}
write.table(arrowhead_data, file = "arrowhead_data.txt",sep="\t",row.names=FALSE)

```

