---
title: "To Do List"
author: "Spiro Stilianoudakis"
date: "May 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Tentative title: "Predictive modeling using genomic annotations: pitfalls and recommendations"

- Do you have an Rmd of this writeup? Make a folder “manuscript”, put it there, make subfolders “figures”, “tables”, “supplementary”, start to compile figures there, it is possible to rename them with “git mv” as we work along
- Make a bulletpoint outline of the results section (same for any section). Each point is a message, and should have a figure or a table that tells this message. See Mourad paper, and other papers, how headers tell the story.
- AUROC numbers are very similar, so are the plots. See the attached, generate tables with the metrics there. We may have a better representation with MCC or F1 measures
- Define distance in the Methods. Currently, it is unclear how distance for, say, A or B compartments, is defined. 
    - For each feature with distance, what is the min-mean-median-max distance ranges? 
    - It a feature-distance is significant, what is the mean-median distance to TAD boundary?

- Figure showing TAD prediction performance on different chromosomes, at different resolutions

- Separate feature selection from chromosome-specific models, selecting consensus features, predicting new TAD boundaries using them. What is the minimum size of a predicted TAD boundary?

- In addition to log2-transformation of distances, use an inverse hyperbolic sine transform. This transformation, which has been used in previous studies of epigenomic maps [Segway paper, PMID: 22426492], is similar to a log transform, but is defined for zero values. Does it improve performance?

### 05/11/18

* Explore the relationship between TAD boundaries and subcompartment intervals using logistic regression

* Set up the equation as follows: $Y_{i} = \beta_{0} + \beta_{1}A +\beta_{2}B$, where Y represents whether there was an overlap bwtween a flanked TAD boundary and a subcompartment (A or B).

* We use a logistic regression model set up: $logit[\pi(x)] = \beta_{0} + \beta_{1}A +\beta_{2}B$, where $\pi(x) = P(Y=1)$ at values x=(A,B).

* Attempt to incorporate distance:
    + Left
    + Right
    + Closest
    
* Explore the correlation between A and B
    

### 06/06/18

* Change structure of categorical variables to factors
* Do log2 transformation then standardize inside train function. Try without log2 transformation and compare
* Change sampling to with replacement (bootstrap)
* For SMOTE generate data and test results for perc.over/perc.under
*Think about how to use figures and tables to tell a story

