---
title: 'Measuring Performance: Evaluating Normalization'
author: "Spiro Stilianoudakis"
output:
  pdf_document:
    toc: yes
  html_document:
    df_print: paged
    toc: yes
  word_document:
    fig_caption: yes
    fig_height: 3
    fig_width: 2
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Packages

```{r}
library(caret)
#library(data.table)
library(gbm)
library(pROC)
library(plyr)
library(dplyr)
#library(DMwR)
library(gridExtra)
library(ggplot2)
library(leaps)
library(knitr)
```

# Setting Working directory

```{r}
setwd("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization")
```

# Log tranformed and standardized

```{r}
enetlst_ls <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetlst_ls.rds")

#Mean AUC across 100 bootstrap samples
enetlst_ls[[3]]

auc.ls <- round(mean(enetlst_ls[[3]]),3)
auc.ls

#roc curve
fpr.ls <- rowMeans(enetlst_ls[[2]])
tpr.ls <- rowMeans(enetlst_ls[[1]])
rocdat.ls <- data.frame(fpr=fpr.ls, tpr=tpr.ls)
ggplot(rocdat.ls, aes(x=fpr, y=tpr)) + 
  geom_line(size=1, color="#4D4D4D") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve: Log Transformed & Standardized")

varimp.ls <- as.vector(rowMeans(enetlst_ls[[4]]))
Labels <- rownames(enetlst_ls[[4]])
Labels[grep("Gm12878_", Labels)] <- gsub("Gm12878_","",Labels[grep("Gm12878_", Labels)])
varimp.ls.df <- data.frame(Feature=Labels,
                                 Importance=varimp.ls)
varimp.ls.df <- varimp.ls.df[order(varimp.ls.df$Importance),]
varimp.ls.df <- varimp.ls.df[(dim(varimp.ls.df)[1]-19):dim(varimp.ls.df)[1],]
varimp.ls.df$Feature <- factor(varimp.ls.df$Feature,
                                     levels=varimp.ls.df$Feature)
p.ls <- ggplot(varimp.ls.df, aes(x=Feature, y=Importance)) +
  xlab("Predictors") +
  ylab("Importance") +
  #ggtitle("Importance Plot for Gradient Boosting Machine") +
  geom_bar(stat="identity", 
           width=.5, 
           position="dodge",
           fill="#4D4D4D") +
  coord_flip() +
  theme_minimal() +
  ggtitle("Log Transformed \n & Standardized")
p.ls

```

# Log tranformed and un-standardized

```{r}
enetlst_lns <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetlst_lns.rds")

#Mean AUC across 100 bootstrap samples
enetlst_lns[[3]]

auc.lns <- round(mean(enetlst_lns[[3]]),3)
auc.lns

#roc curve
fpr.lns <- rowMeans(enetlst_lns[[2]])
tpr.lns <- rowMeans(enetlst_lns[[1]])
rocdat.lns <- data.frame(fpr=fpr.lns, tpr=tpr.lns)
ggplot(rocdat.lns, aes(x=fpr.lns, y=tpr.lns)) + 
  geom_line(size=1, color="#000000") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve: Log Transformed & Un-Standardized")

varimp.lns <- as.vector(rowMeans(enetlst_lns[[4]]))
Labels <- rownames(enetlst_lns[[4]])
Labels[grep("Gm12878_", Labels)] <- gsub("Gm12878_","",Labels[grep("Gm12878_", Labels)])
varimp.lns.df <- data.frame(Feature=Labels,
                                 Importance=varimp.lns)
varimp.lns.df <- varimp.lns.df[order(varimp.lns.df$Importance),]
varimp.lns.df <- varimp.lns.df[(dim(varimp.lns.df)[1]-19):dim(varimp.lns.df)[1],]
varimp.lns.df$Feature <- factor(varimp.lns.df$Feature,
                                     levels=varimp.lns.df$Feature)
p.lns <- ggplot(varimp.lns.df, aes(x=Feature, y=Importance)) +
  xlab("Predictors") +
  ylab("Importance") +
  #ggtitle("Importance Plot for Gradient Boosting Machine") +
  geom_bar(stat="identity", 
           width=.5, 
           position="dodge",
           fill="#000000") +
  coord_flip() +
  theme_minimal() +
  ggtitle("Log Transformed \n & Un-Standardized")
p.lns

```


# Not Log tranformed and Standardized

```{r}
enetlst_nls <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetlst_nls.rds")

#Mean AUC across 100 bootstrap samples
enetlst_nls[[3]]

auc.nls <- round(mean(enetlst_nls[[3]]),3)
auc.nls

#roc curve
fpr.nls <- rowMeans(enetlst_nls[[2]])
tpr.nls <- rowMeans(enetlst_nls[[1]])
rocdat.nls <- data.frame(fpr=fpr.nls, tpr=tpr.nls)
ggplot(rocdat.nls, aes(x=fpr.nls, y=tpr.nls)) + 
  geom_line(size=1, color="#E6E6E6") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve: Not Log Transformed & Standardized")

varimp.nls <- as.vector(rowMeans(enetlst_nls[[4]]))
Labels <- rownames(enetlst_nls[[4]])
Labels[grep("Gm12878_", Labels)] <- gsub("Gm12878_","",Labels[grep("Gm12878_", Labels)])
varimp.nls.df <- data.frame(Feature=Labels,
                                 Importance=varimp.nls)
varimp.nls.df <- varimp.nls.df[order(varimp.nls.df$Importance),]
varimp.nls.df <- varimp.nls.df[(dim(varimp.nls.df)[1]-19):dim(varimp.nls.df)[1],]
varimp.nls.df$Feature <- factor(varimp.nls.df$Feature,
                                     levels=varimp.nls.df$Feature)
p.nls <- ggplot(varimp.nls.df, aes(x=Feature, y=Importance)) +
  xlab("Predictors") +
  ylab("Importance") +
  #ggtitle("Importance Plot for Gradient Boosting Machine") +
  geom_bar(stat="identity", 
           width=.5, 
           position="dodge",
           fill="#E6E6E6") +
  coord_flip() +
  theme_minimal() +
  ggtitle("Not Log Transformed \n & Standardized")
p.nls

```


# Not Log tranformed and Un-Standardized

```{r}
enetlst_nlns <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetlst_nlns.rds")

#Mean AUC across 100 bootstrap samples
enetlst_nlns[[3]]

auc.nlns <- round(mean(enetlst_nlns[[3]]),3)
auc.nlns

#roc curve
fpr.nlns <- rowMeans(enetlst_nlns[[2]])
tpr.nlns <- rowMeans(enetlst_nlns[[1]])
rocdat.nlns <- data.frame(fpr=fpr.nlns, tpr=tpr.nlns)
ggplot(rocdat.nlns, aes(x=fpr.nlns, y=tpr.nlns)) + 
  geom_line(size=1, color="#999999") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve: Not Log Transformed & Un-Standardized")

varimp.nlns <- as.vector(rowMeans(enetlst_nlns[[4]]))
Labels <- rownames(enetlst_nlns[[4]])
Labels[grep("Gm12878_", Labels)] <- gsub("Gm12878_","",Labels[grep("Gm12878_", Labels)])
varimp.nlns.df <- data.frame(Feature=Labels,
                                 Importance=varimp.nlns)
varimp.nlns.df <- varimp.nlns.df[order(varimp.nlns.df$Importance),]
varimp.nlns.df <- varimp.nlns.df[(dim(varimp.nlns.df)[1]-19):dim(varimp.nlns.df)[1],]
varimp.nlns.df$Feature <- factor(varimp.nlns.df$Feature,
                                     levels=varimp.nlns.df$Feature)
p.nlns <- ggplot(varimp.nlns.df, aes(x=Feature, y=Importance)) +
  xlab("Predictors") +
  ylab("Importance") +
  #ggtitle("Importance Plot for Gradient Boosting Machine") +
  geom_bar(stat="identity", 
           width=.5, 
           position="dodge",
           fill="#999999") +
  coord_flip() +
  theme_minimal() +
  ggtitle("Not Log Transformed \n & Standardized")
p.nlns

```

# Comparing additional performance metrics across all normalization techniques

```{r}

options(scipen = 999)

enetperf_ls <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetperf_ls.rds")

enetperf_lns <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetperf_lns.rds")

enetperf_nls <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetperf_nls.rds")

enetperf_nlns <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/comparing_normalization/enetperf_nlns.rds")

lstab <- round(as.matrix(rowMeans(enetperf_ls)),2)
lnstab <- round(as.matrix(rowMeans(enetperf_lns)),2)
nlstab <- round(as.matrix(rowMeans(enetperf_nls)),2)
nlnstab <- round(as.matrix(rowMeans(enetperf_nlns)),2)

lstab[1:5,1] <- round(lstab[1:5,1],0)
lnstab[1:5,1] <- round(lnstab[1:5,1],0)
nlstab[1:5,1] <- round(nlstab[1:5,1],0)
nlnstab[1:5,1] <- round(nlnstab[1:5,1],0)

perfdat <- cbind.data.frame(rownames(enetperf_ls), 
                            lstab,
                            lnstab,
                            nlstab,
                            nlnstab)
rownames(perfdat) <- NULL
colnames(perfdat) <- c("Metric", "Log/Std", "Log/Un-Std", "No Log/Std", "No Log/Un-Std")

kable(perfdat)
```


# Comparing Models

```{r}
auc.plot <- data.frame("Normalization Technique"=c("Log/Standardaized", 
                                       "Log/Un-Standardaized",
                                       "No Log/Standardaized",
                                       "No Log/Un-Standardaized"),
                       auc=c(auc.ls,
                             auc.lns,
                             auc.nls,
                             auc.nlns))

auc.plot <- auc.plot[order(auc.plot$auc, decreasing=TRUE),]

auc.plot$Normalization.Technique <-factor(auc.plot$Normalization.Technique, 
                                     levels=auc.plot$Normalization.Technique)

p<-ggplot(data=auc.plot, aes(x=Normalization.Technique, y=auc, fill=Normalization.Technique)) + 
  xlab("Normalization Technique") + ylab("AUC") +
  geom_bar(stat="identity") + ylim(0,1) +
  scale_fill_manual(values=grey(c(0,.3,.6,.9)), guide=FALSE) +
  scale_x_discrete(labels= c("Log/ \n Un-Standardaized", 
             "Log/ \n Standardaized",
             "No Log/ \n Un-Standardaized",
              "No Log/ \n Standardaized")) + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Model Performance for Different \n Normalization Techniques")
p

#datatable(auc.plot)
kable(auc.plot)

rocdat.ls$Technique <- "ls"
rocdat.lns$Technique <- "lns"
rocdat.nls$Technique <- "nls"
rocdat.nlns$Technique <- "nlns"
allrocdat <- rbind.data.frame(rocdat.ls, rocdat.lns, rocdat.nls, rocdat.nlns)

ggplot(data=allrocdat, aes(x=fpr, y=tpr, color=Technique)) + 
  geom_line(size=1) +
  scale_colour_manual(name="Technique",
    labels=c("Log/ \n Un-Standardaized", 
             "Log/ \n Standardaized",
             "No Log/ \n Un-Standardaized",
              "No Log/ \n Standardaized"),
    values=grey(c(0,.3,.6,.9))) + 
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curves for Different \n Normalization Techniques")

grid.arrange(p.ls,p.lns,p.nls,p.nlns,ncol=2)

```

