---
title: "Modelling Chromosome 1"
author: "Spiro Stilianoudakis"
date: "May 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r }

library(caret)
library(data.table)
library(gbm)
library(pROC)
library(plyr)
library(dplyr)
library(DMwR)
library(gridExtra)


```

# Reading in data

```{r}

setwd("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878")

#chromosome 1 filtered/log transformed/no standardization/forward selection

chr1_gm12878_fwd <- readRDS("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/chr1_gm12878_fwd.rds")


```


#set number of bootstrap samples

```{r}

bootsamps = 10

```

#set tuning parameters

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 5,
                           ## Estimate class probabilities
                           classProbs = TRUE,
                           ## Evaluate performance using 
                           ## the following function
                           summaryFunction = twoClassSummary)

```

#create a matrix of row ids that represent the zero class


```{r}
##the number of rows will match the one class
##the number of columns match the number of bootstrap samples


sampids <- matrix(ncol=bootsamps, 
                  nrow=length(chr1_gm12878_fwd$y[which(chr1_gm12878_fwd$y=="Yes")]))


```

#filling in the sample ids matrix

```{r}
set.seed(123)
for(j in 1:bootsamps){
  sampids[,j] <- sample(which(chr1_gm12878_fwd$y=="No"),
                        length(which(chr1_gm12878_fwd$y=="Yes")),
                        replace = TRUE)
}

```

#function for roc curves

```{r}
simple_roc <- function(labels, scores){
  labels <- labels[order(scores, decreasing=TRUE)]
  data.frame(TPR=cumsum(labels)/sum(labels), FPR=cumsum(!labels)/sum(!labels), labels)
}

```


# Random Forest

```{r include=FALSE}

#set length of list objects that will be filled in with specificities
#and sensitivities and aucs and variable importance
rflst <- list(tpr <- matrix(nrow=ceiling((length(which(chr1_gm12878_fwd$y=="Yes"))*2)*.3), 
                              ncol=bootsamps),
                fpr <- matrix(nrow=ceiling((length(which(chr1_gm12878_fwd$y=="Yes"))*2)*.3), 
                              ncol=bootsamps),
                auc <- numeric(bootsamps),
                varimp <- matrix(nrow=dim(chr1_gm12878_fwd)[2]-1,
                                 ncol=bootsamps))
rownames(rflst[[4]]) <- colnames(chr1_gm12878_fwd)[-1]

# Random Forest


#set length of list objects that will be filled in with specificities
#and sensitivities and aucs and variable importance
rflst <- list(tpr <- matrix(nrow=ceiling((length(which(chr1_gm12878_fwd$y=="Yes"))*2)*.3), 
                              ncol=bootsamps),
                fpr <- matrix(nrow=ceiling((length(which(chr1_gm12878_fwd$y=="Yes"))*2)*.3), 
                              ncol=bootsamps),
                auc <- numeric(bootsamps),
                varimp <- matrix(nrow=dim(chr1_gm12878_fwd)[2]-1,
                                 ncol=bootsamps))
rownames(rflst[[4]]) <- colnames(chr1_gm12878_fwd)[-1]

rfperf <- matrix(nrow = 16, ncol=bootsamps)
rownames(rfperf) <- c("TN",
 							"FN",
 							"FP",
 							"TP",
 							"Total",
							"Sensitivity",
 							"Specificity",
 							"Kappa",
 							"Accuracy",
 							"Precision",
 							"FPR",
 							"FNR",
 							"FOR",
 							"NPV",
 							"MCC",
 							"F1")

#Performing Random Forest

for(i in 1:bootsamps){

  #combining the two classes to create balanced data
  data <- rbind.data.frame(chr1_gm12878_fwd[which(chr1_gm12878_fwd$y=="Yes"),],
                           chr1_gm12878_fwd[sampids[,i],])
  
  #determining the best number of variables randomly sampled as candidates at each split
  set.seed(5430)
  bestmtry <- tuneRF(data[,-1],data$y,
                   improve=.01,trace=0,plot=F) 
  bestmtry <- data.frame(bestmtry)
  bestmtry <- bestmtry[order(bestmtry$OOBError, decreasing = FALSE),]
  #bestmtry$mtry[1]

  #splitting the data
  inTrainingSet <- sample(length(data$y),floor(length(data$y)*.7))
  #inTrainingSet <- createDataPartition(data$y,p=.7,list=FALSE)
  train <- data[inTrainingSet,]
  test <- data[-inTrainingSet,]
  
  #determining best number of trees
  tunegrid <- expand.grid(.mtry=bestmtry$mtry[1])
  modellist <- list()
    for (ntree in c(50,200,500,1000)) {
      set.seed(333)
      fit <- train(y~., data=train, 
                   method="rf", 
                   metric="Accuracy",
                   tuneGrid=tunegrid,  
                   ntree=ntree)
      key <- toString(ntree)
      modellist[[key]] <- fit
    }
    # compare results
    results <- resamples(modellist)
    #summary(results)
    #dotplot(results)
    results <- data.frame(summary(results)[3]$statistics$Accuracy)
    results <- results[order(results$Mean, decreasing = TRUE),]

  set.seed(1006)
  rfModel <- train(y~., data=train, 
                    method="rf", 
                    metric="ROC", 
                    tuneGrid=tunegrid, 
                    trControl=fitControl, 
                    ntree=as.numeric(rownames(results)[1]))

  #Prediction vector for ROC and AUC
  pred.rfModel <- as.vector(predict(rfModel, 
                                    newdata=test, 
                                    type="prob")[,"Yes"])
  rflst[[1]][,i] <- simple_roc(ifelse(test$y=="Yes",1,0),pred.rfModel)[,1]
  rflst[[2]][,i] <- simple_roc(ifelse(test$y=="Yes",1,0),pred.rfModel)[,2]
  rflst[[3]][i] <- pROC::auc(pROC::roc(test$y, pred.rfModel))
  rflst[[4]][,i] <- varImp(rfModel)$importance[,1]
  
  #Prediction vector for other performance metrics
  pred.rfModel2 <- predict(rfModel,
                                     newdata=test,
                                     type="raw")
  confMat <- confusionMatrix(data=pred.rfModel2, test$y, positive="Yes")
  TN = as.numeric(confMat$table[1,1])
  FN = as.numeric(confMat$table[1,2])
  FP = as.numeric(confMat$table[2,1])
  TP = as.numeric(confMat$table[2,2])
  rfperf[1,i] <- confMat$table[1,1]
  rfperf[2,i] <- confMat$table[1,2]
  rfperf[3,i] <- confMat$table[2,1]
  rfperf[4,i] <- confMat$table[2,2]
  rfperf[5,i] <- sum(confMat$table)
  rfperf[6,i] <- as.vector(confMat$byClass["Sensitivity"])
  rfperf[7,i] <- as.vector(confMat$byClass["Specificity"])
  rfperf[8,i] <- as.vector(confMat$overall["Kappa"])
  rfperf[9,i] <- as.vector(confMat$overall["Accuracy"])
  rfperf[10,i] <- confMat$table[2,2]/(confMat$table[2,2]+confMat$table[2,1])
  rfperf[11,i] <- confMat$table[2,1]/(confMat$table[2,1]+confMat$table[1,1])
  rfperf[12,i] <- confMat$table[1,2]/(confMat$table[1,2]+confMat$table[2,2])
  rfperf[13,i] <- confMat$table[1,2]/(confMat$table[1,2]+confMat$table[1,1])
  rfperf[14,i] <- confMat$table[1,1]/(confMat$table[1,1]+confMat$table[1,2])
  #rfperf[15,i] <- mccr(ifelse(test$y=="Yes",1,0),ifelse(pred.enetModel2=="Yes",1,0))
  rfperf[15,i] <- (TP*TN - FP*FN)/( sqrt( (TP+FP)*(TP+FN)*(TN+FP)*(TN+FN) ) )
  rfperf[16,i] <- (2*(confMat$table[2,2]/(confMat$table[2,2]+confMat$table[1,2]))*(confMat$table[2,2]/(confMat$table[2,2]+confMat$table[2,1])))/(((confMat$table[2,2]/(confMat$table[2,2]+confMat$table[1,2]))*(confMat$table[2,2]/(confMat$table[2,2]+confMat$table[2,1]))) + (confMat$table[2,2]/(confMat$table[2,2]+confMat$table[2,1])))

}


saveRDS(rflst, "rflst.rds")
saveRDS(rfperf, "rfperf.rds")




```

# GBM

```{r}

#set length of list objects that will be filled in with specificities
#and sensitivities and aucs and variable importance
gbmlst <- list(tpr <- matrix(nrow=ceiling((length(which(chr1_gm12878_fwd$y=="Yes"))*2)*.3), 
                            ncol=bootsamps),
              fpr <- matrix(nrow=ceiling((length(which(chr1_gm12878_fwd$y=="Yes"))*2)*.3), 
                            ncol=bootsamps),
              auc <- numeric(bootsamps),
              varimp <- matrix(nrow=dim(chr1_gm12878_fwd)[2]-1,
                               ncol=bootsamps))
rownames(gbmlst[[4]]) <- colnames(chr1_gm12878_fwd)[-1]


#Running GBM Model

for(i in 1:bootsamps){
  
  #combining the two classes to create balanced data
  data <- rbind.data.frame(chr1_gm12878_fwd[which(chr1_gm12878_fwd$y=="Yes"),],
                           chr1_gm12878_fwd[sampids[,i],])
  
  
  set.seed(2244)
  inTrainingSet <- sample(length(data$y),floor(length(data$y)*.7))
  #inTrainingSet <- createDataPartition(data$y,p=.7,list=FALSE)
  train <- data[inTrainingSet,]
  test <- data[-inTrainingSet,]
  
  #GBM
  gbmModel <- train(y ~ ., data=train, 
                    method = "gbm", 
                    metric="ROC", 
                    trControl = fitControl, 
                    verbose=FALSE, 
                    tuneLength=5)
  pred.gbmModel <- as.vector(predict(gbmModel, 
                                     newdata=test, 
                                     type="prob")[,"Yes"])
  gbmlst[[1]][,i] <- simple_roc(ifelse(test$y=="Yes",1,0),pred.gbmModel)[,1]
  gbmlst[[2]][,i] <- simple_roc(ifelse(test$y=="Yes",1,0),pred.gbmModel)[,2]
  gbmlst[[3]][i] <- pROC::auc(pROC::roc(test$y, pred.gbmModel))
  gbmlst[[4]][,i] <- varImp(gbmModel)$importance[,1]
  
}


```

