---
title: "Measuring Performance"
subtitle: "Dimension Reduction Techniques"
author: "Spiro Stilianoudakis"
date: "July 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Packages

```{r}
library(caret)
#library(data.table)
library(gbm)
library(pROC)
library(plyr)
library(dplyr)
#library(DMwR)
library(gridExtra)
library(ggplot2)
library(leaps)
library(limma)
```

# Setting Working directory

```{r}
#reading in dataset
setwd("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878")
chr1_gm12878_f <- readRDS("chr1_gm12878_f.rds")

#set directory for selection techinques
setwd("C:/Users/Spiro Stilianoudakis/Documents/TAD_data/RData/GM12878/variable_reduction")


```

# Variable Selection Techniques

## Forward Selection

```{r}
auc.model.fwd <- readRDS("auc.model.fwd.rds")
cv.preds.fwd <- readRDS("cv.preds.fwd.rds")
roc.model.fwd <- readRDS("roc.model.fwd.rds")

auc.fwd <- round(max(auc.model.fwd),3)
auc.fwd
#0.862

vars.fwd <- na.omit(cv.preds.fwd[,which.max(auc.model.fwd)])
vars.fwd[grep("_dist",vars.fwd,invert = TRUE)] <- unlist(lapply(vars.fwd[grep("_dist",vars.fwd,invert = TRUE)], function(x){substr(x,1,nchar(x)-1)}))
 
chr1_gm12878_fwd <- chr1_gm12878_f[,which((names(chr1_gm12878_f) %in% vars.fwd) | names(chr1_gm12878_f)=="y")]
 
dim(chr1_gm12878_fwd)
#3258   29
 
names(chr1_gm12878_fwd)

 [1] "y"                             "complex_dist"                  "inversion_dist"               
 [4] "mobile_element_insertion_dist" "low_complexity_dist"           "LTR_dist"                     
 [7] "RC_dist"                       "Gm12878_WeakTxn"               "Gm12878_Heterochromlo"        
[10] "Gm12878_TxnElongation_dist"    "Gm12878_WeakTxn_dist"          "Gm12878_Heterochromlo_dist"   
[13] "Gm12878_WeakPromoter_dist"     "Gm12878_Insulator_dist"        "Gm12878_T"                    
[16] "Gm12878_CTCF_dist"             "Gm12878_PF_dist"               "Gm12878_T_dist"               
[19] "Gm12878_TSS_dist"              "Gm12878_DNaseI"                "Gm12878_DNaseI_dist"          
[22] "Gm12878_H3k27ac"               "Gm12878_H3k9ac"                "Gm12878_H4k20me1"             
[25] "Gm12878_H2az_dist"             "Gm12878_H3k36me3_dist"         "Gm12878_H3k9ac_dist"          
[28] "Gm12878_H3k9me3_dist"          "Gm12878_H4k20me1_dist" 

rocdat.fwd <- data.frame(sensitivity=roc.model.fwd$sensitivities, specificity=1-roc.model.fwd$specificities)
rocdat.fwd$Selection <- "fwd"

ggplot(rocdat.fwd, aes(x=specificity, y=sensitivity)) + 
  geom_line(size=1, color="red") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve for Forward Selection")


```


## Backward Selection

```{r}
auc.model.bwd <- readRDS("auc.model.bwd.rds")
cv.preds.bwd <- readRDS("cv.preds.bwd.rds")
roc.model.bwd <- readRDS("roc.model.bwd.rds")

auc.bwd <- round(max(auc.model.bwd),3)
auc.bwd
#0.87

vars.bwd <- na.omit(cv.preds.bwd[,which.max(auc.model.bwd)])
vars.bwd[grep("_dist",vars.bwd,invert = TRUE)] <- unlist(lapply(vars.bwd[grep("_dist",vars.bwd,invert = TRUE)], function(x){substr(x,1,nchar(x)-1)}))
 
chr1_gm12878_bwd <- chr1_gm12878_f[,which((names(chr1_gm12878_f) %in% vars.bwd) | names(chr1_gm12878_f)=="y")]
 
dim(chr1_gm12878_bwd)
#247632     35 
 
names(chr1_gm12878_bwd)
 [1] "y"                             "A"                             "B"                            
 [4] "complex_dist"                  "inversion_dist"                "mobile_element_insertion_dist"
 [7] "SINE"                          "low_complexity_dist"           "LTR_dist"                     
[10] "RC_dist"                       "SINE_dist"                     "Gm12878_WeakTxn"              
[13] "Gm12878_Repressed"             "Gm12878_Heterochromlo"         "Gm12878_TxnElongation_dist"   
[16] "Gm12878_WeakTxn_dist"          "Gm12878_Repressed_dist"        "Gm12878_Heterochromlo_dist"   
[19] "Gm12878_WeakPromoter_dist"     "Gm12878_Insulator_dist"        "Gm12878_T"                    
[22] "Gm12878_CTCF_dist"             "Gm12878_T_dist"                "Gm12878_TSS_dist"             
[25] "Gm12878_DNaseI"                "Gm12878_DNaseI_dist"           "Gm12878_H3k27ac"              
[28] "Gm12878_H3k36me3"              "Gm12878_H3k9ac"                "Gm12878_H4k20me1"             
[31] "Gm12878_H2az_dist"             "Gm12878_H3k4me2_dist"          "Gm12878_H3k9ac_dist"          
[34] "Gm12878_H3k9me3_dist"          "Gm12878_H4k20me1_dist"


rocdat.bwd <- data.frame(sensitivity=roc.model.bwd$sensitivities, specificity=1-roc.model.bwd$specificities)
rocdat.bwd$Selection <- "bwd"

ggplot(rocdat.bwd, aes(x=specificity, y=sensitivity)) + 
  geom_line(size=1, color="blue") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve for Backward Selection")

```


## Both

```{r}
auc.model.both <- readRDS("auc.model.both.rds")
cv.preds.both <- readRDS("cv.preds.both.rds")
roc.model.both <- readRDS("roc.model.both.rds")

auc.both <- round(max(auc.model.both),3)
auc.both
#0.866

vars.both <- na.omit(cv.preds.both[,which.max(auc.model.both)])
vars.both[grep("_dist",vars.both,invert = TRUE)] <- unlist(lapply(vars.both[grep("_dist",vars.both,invert = TRUE)], function(x){substr(x,1,nchar(x)-1)}))
 
chr1_gm12878_both <- chr1_gm12878_f[,which((names(chr1_gm12878_f) %in% vars.both) | names(chr1_gm12878_f)=="y")]
 
dim(chr1_gm12878_both)
#247632     27
 
names(chr1_gm12878_both)
 [1] "y"                             "complex_dist"                  "mobile_element_insertion_dist"
 [4] "low_complexity_dist"           "LTR_dist"                      "Gm12878_Heterochromlo"        
 [7] "Gm12878_TxnElongation_dist"    "Gm12878_WeakTxn_dist"          "Gm12878_Heterochromlo_dist"   
[10] "Gm12878_Insulator_dist"        "Gm12878_R"                     "Gm12878_T"                    
[13] "Gm12878_CTCF_dist"             "Gm12878_PF_dist"               "Gm12878_TSS_dist"             
[16] "Gm12878_DNaseI"                "Gm12878_DNaseI_dist"           "Gm12878_H3k27ac"              
[19] "Gm12878_H3k79me2"              "Gm12878_H3k9ac"                "Gm12878_H3k9me3"              
[22] "Gm12878_H4k20me1"              "Gm12878_H2az_dist"             "Gm12878_H3k36me3_dist"        
[25] "Gm12878_H3k4me2_dist"          "Gm12878_H3k9ac_dist"           "Gm12878_H4k20me1_dist"

rocdat.both <- data.frame(sensitivity=roc.model.both$sensitivities, specificity=1-roc.model.both$specificities)
rocdat.both$Selection <- "both"

ggplot(rocdat.both, aes(x=specificity, y=sensitivity)) + 
  geom_line(size=1, color="green") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve for Both")

```


# RFE

```{r}
rfeModel <- readRDS("rfeModel.rds")
roc.rfeModel <- readRDS("roc.rfeModel.rds")

auc. rfe <- round(pROC::auc(roc.rfeModel),3)
#0.7986

plot(rfeModel, type="b")

accdat <- rfeModel$results 
accdat <- accdat[order(accdat$Accuracy, decreasing = TRUE),]

predictors(rfeModel)
 [1] "Gm12878_Insulator_dist"        "Gm12878_CTCF_dist"             "Gm12878_DNaseI_dist"          
 [4] "Gm12878_H2az_dist"             "Gm12878_TSS_dist"              "Gm12878_H3k9ac_dist"          
 [7] "Gm12878_PF_dist"               "Gm12878_WeakPromoter_dist"     "Gm12878_ActivePromoter_dist"  
[10] "Gm12878_H3k79me2_dist"         "Gm12878_H3k4me2_dist"          "Gm12878_H3k27ac_dist"         
[13] "Gm12878_WeakTxn_dist"          "Gm12878_H3k36me3_dist"         "Gm12878_TxnElongation_dist"   
[16] "Gm12878_StrongEnhancer5_dist"  "Gm12878_StrongEnhancer4_dist"  "Gm12878_H3k4me1_dist"         
[19] "se_GM12878_dist"               "Gm12878_WE_dist"               "Gm12878_H3k4me3_dist"         
[22] "Gm12878_H4k20me1_dist"         "VMR_dist"                      "Gm12878_WeakEnhancer6_dist"   
[25] "Gm12878_H3k27me3_dist"         "Gm12878_TxnTransition_dist"    "Gm12878_E_dist"               
[28] "Gm12878_Repressed_dist"        "DNA_dist"                      "Gm12878_R_dist"               
[31] "Gm12878_H3k9me3_dist"          "Gm12878_Heterochromlo_dist"    "A"                            
[34] "Gm12878_PoisedPromoter_dist"   "UCNE_dist"                     "Gm12878_DNaseI"               
[37] "Gm12878_T_dist"                "SINE_dist"                     "simple_repeat_dist"           
[40] "sequence_alteration_dist"      "novel_sequence_insertion_dist" "Gm12878_WeakEnhancer7_dist"   
[43] "Gm12878_H3k36me3"              "duplication_dist"              "Gm12878_H2az"                 
[46] "Gm12878_RepetitiveCNV15_dist"  "LTR_dist"                      "tandem_duplication_dist"


rocdat.rfe <- data.frame(sensitivity=roc.rfeModel$sensitivities, specificity=1-roc.rfeModel$specificities)
rocdat.rfe$Selection <- "rfe"

ggplot(rocdat.rfe, aes(x=specificity, y=sensitivity)) + 
  geom_line(size=1, color="black") +
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curve for RFE")

```


# Comparing Variable Selection Techniques

```{r}
auc.plot <- data.frame(Selection=c("Forward", 
                                       "Backward",
                                       "Both",
                                       "RFE"),
                       auc=c(auc.fwd,
                             auc.bwd,
                             auc.both,
                             auc.rfe))

auc.plot <- auc.plot[order(auc.plot$auc, decreasing=TRUE),]

auc.plot$Selection <-factor(auc.plot$Selection, 
                                     levels=auc.plot$Selection)

p<-ggplot(data=auc.plot, aes(x=Selection, y=auc, fill=Selection)) + 
  xlab("Variable Selection Technique") + ylab("AUC") +
  geom_bar(stat="identity") + ylim(0,1) +
  scale_fill_manual(values=c("red", "blue", "green", "black"), guide=FALSE) +
  annotate("text", x=1, y=1, label= "29", size=6) +
  annotate("text", x=2, y=1, label= "35", size=6) +
  annotate("text", x=3, y=1, label= "27", size=6) +
  annotate("text", x=4, y=1, label= "48", size=6) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Model Performance for Different \n Variable Selection Techniques")
p


allrocdat <- rbind.data.frame(rocdat.fwd, rocdat.bwd, rocdat.both, rocdat.rfe)

ggplot(data=allrocdat, aes(x=specificity, y=sensitivity, color=Selection)) + 
  geom_line(size=1) +
  scale_colour_manual(name="Technique",
    labels=c("Forward", 
             "Backward",
             "Both",
              "RFE"),
    values=c("green", "red", "blue", "black")) + 
  xlab("1-Specificity") + 
  ylab("Sensitivity") + 
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(intercept=0, slope=1) +
  theme_minimal() +
  ggtitle("ROC Curves for Different \n Variable Selection Techniques")


intersect(vars.fwd,intersect(vars.bwd,vars.both))
intersect(vars.fwd,intersect(vars.bwd,predictors(rfeModel)))
intersect(intersect(vars.fwd,intersect(vars.bwd,vars.both)),
          intersect(vars.fwd,intersect(vars.bwd,predictors(rfeModel))))

fwd <- (names(chr1_gm12878_f) %in% vars.fwd)
bwd <- (names(chr1_gm12878_f) %in% vars.bwd)
both <- (names(chr1_gm12878_f) %in% vars.both)
rfe <- (names(chr1_gm12878_f) %in% predictors(rfeModel))


venndat1 <- cbind(fwd,bwd,both)
venndat2 <- cbind(fwd,bwd,rfe)

a <- vennCounts(venndat1)
b <- vennCounts(venndat2)

vennDiagram(a)
vennDiagram(b)

vennDiagram(a, include = "both", 
  names = c("Forward", "Backward", "Both"), 
  cex = 1, counts.col = "red")

vennDiagram(b, include = "both", 
  names = c("Forward", "Backward", "RFE"), 
  cex = 1, counts.col = "red")
```

